backend/admin_app/urls.py
from django.urls import path
from .views.admin_homepage_view import BaseAdminView
from .views.user_update_view import UserUpdateView
from .views.blocked_users_view import BlockedUsersView
from .views.unverified_users_view import UnverifiedUsersView

urlpatterns = [
    path('', BaseAdminView.as_view(), name='admin_homepage'),
    path('user/<int:pk>/edit/', UserUpdateView.as_view(), name='user_edit'),
    path('blocked-users', BlockedUsersView.as_view(), name='blocked-users'),
    path('unverified-users', UnverifiedUsersView.as_view(), name='unverified-users'),
]

backend/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from project import settings
from users.views.views import HomeStub

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('users/', include('users.urls')),
    path('api/user/', include('user_api.urls')),
    path('api/v0/', include('api_v0.urls')),
    path('administrator/', include('admin_app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

backend/users/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth
from users.views.registration import Register


urlpatterns = [
    path(
        "login/", auth.LoginView.as_view(
            template_name="auth/login.html",
            success_url="homepage",
        ), name="user-login"
    ),
    path("logout/", auth.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        auth.PasswordChangeView.as_view(
            template_name='auth/change_password.html',
            success_url='/users/password_changed/'
        ),
        name="password_change"
    ),
    path(
        "password_changed/",
        auth.PasswordChangeDoneView.as_view(
            template_name='auth/password_changed.html',
        ),
        name="password_changed",
    ),
    path(
        "password_reset/",
        auth.PasswordResetView.as_view(),
        name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path('register/', Register.as_view(), name='user-register'),
]

backend/users/models/users.py
from __future__ import unicode_literals

import random
from datetime import timedelta

from django.contrib.auth.base_user import BaseUserManager
from django.core.signing import Signer
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractUser
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.hashers import make_password
from django.utils import timezone
from django.contrib.auth.password_validation import validate_password

from project import settings


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        if not password:
            raise ValueError('The password must be set')
        if not validate_password(password, user=None):
            raise ValueError('The given password must be at least 8 characters long')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError('The mail id must be set')
        if not password:
            raise ValueError('The password must be set')

        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('email_confirmed', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    # поле не обязательно, но нужно для работы системы
    username = models.CharField(_('username'), max_length=32, unique=False, null=True, blank=True)
    first_name = models.CharField(_('first name'), max_length=100, blank=True)
    last_name = models.CharField(_('last name'), max_length=100, blank=True)
    patronymic = models.CharField(_('Отчество'), max_length=100, blank=True)
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    is_staff = models.BooleanField(_('staff'), default=False)
    is_active = models.BooleanField(_('active'), default=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    email_confirmed = models.BooleanField(
        default=False,
        verbose_name='Подтверждение почты',
        blank=True,
        null=True,
        help_text='Прошел ли пользователь проверку почты после регистрации.'
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def is_doctor(self) -> bool:
        return self.groups.filter(name='Doctors').exists()

    def is_administrator(self) -> bool:
        return self.groups.filter(name='Administrators').exists()

    def check_delete_if_inactive_unconfirmed(self) -> bool:
        """
        Удаляет текущего пользователя, если он неактивен и у него отсутствует подтверждение email.
        """
        if not self.email_confirmed and not self.is_active:
            tokens = EmailConfirmationToken.objects.filter(user=self)
            if not tokens.exists() or all(token.has_expired() for token in tokens):
                self.delete()
                return True
        return False


class EmailConfirmationToken(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(
        max_length=255,
        unique=True,
        verbose_name='Токен подтверждения почты.',
        help_text='Токен который указывается в GET запросе на подтверждения почты.\n'
                  'Состоит из id пользователя и email, зашифрованных django.signer.'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Время создания токена.'
    )

    is_changing_email = models.BooleanField(
        default=False,
        verbose_name='Флаг ',
        help_text='Флаг для токена,назначается в случае если пользователь решил изменить '
                  'почту (или зарегистрироваться).\n'
                  'В случае если пользователь регистрируется = False. В ином True.'
    )

    changed_email = models.EmailField(
        blank=True,
        help_text='Почта на которую пользователь хочет изменить свою текущую.'
    )

    def has_expired(self) -> bool:
        """
        Проверка действительности токена подтверждения почты
        Метод удалит токен если он уже был просрочен
        :return: Возвращает True если токен просрочен и уже недействителен
        """

        expiration_time = timedelta(minutes=settings.EMAIL_CONFIRMATION_TOKEN_LIFETIME)
        response = timezone.now() > self.created_at + expiration_time

        if response:
            self.delete()
        return response

    def __str__(self):
        return f"Email change token for {self.user.email}"


class PasswordChangeToken(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(
        verbose_name='Токен смены пароля.',
        help_text='6-ти значный код из цифр.'
    )

    url = models.CharField(
        verbose_name='URL для смены пароля.',
        help_text='Уникальный url для смены пароля.'
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Время создания токена.'
    )

    def has_expired(self) -> bool:
        """
        Проверка действительности токена подтверждения пароля
        Метод удалит токен если он уже был просрочен
        :return: Возвращает True если токен просрочен и уже недействителен
        """

        expiration_time = timedelta(minutes=settings.EMAIL_CONFIRMATION_TOKEN_LIFETIME)
        response = timezone.now() > self.created_at + expiration_time

        if response:
            self.delete()
        return response

    def url_generator(self):
        signer = Signer()
        self.url = signer.sign_object(f'{self.user.id}%{self.user.email}')
        return f"{self.url}"

    def save(self, *args, **kwargs):
        """
        Переопределяем метод save, чтобы автоматически генерировать
        6-значный токен и URL перед сохранением объекта в базе данных.
        """
        PasswordChangeToken.objects.filter(user=self.user).delete()

        if not self.token:
            self.token = str(random.randint(100000, 999999))  # Генерируем 6-значный токен

        if not self.url:
            self.url = self.url_generator()  # Генерируем URL

        super().save(*args, **kwargs)  # Вызываем стандартный метод сохранения

    def __str__(self):
        return f"Password change token for {self.user.email}"

backend/admin_app/views/admin_homepage_view.py
import re

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from django.shortcuts import redirect
from users.models.users import User
from admin_app.utils.access_rights import AccessUtils
from project.settings import SITE_URL


MONTHS_RU_TO_NUM = {
    'январ': 1, 'феврал': 2, 'март': 3, 'апрел': 4, 'ма': 5, 'июн': 6,
    'июл': 7, 'август': 8, 'сентябр': 9, 'октябр': 10, 'ноябр': 11, 'декабр': 12
}

def normalize_month_name(month_name):
    # Преобразуем в нижний регистр и убираем окончания
    month_name = month_name.lower().strip()
    # Обрабатываем окончания
    for month in MONTHS_RU_TO_NUM.keys():
        if month_name.startswith(month):
            return month
    return None

class BaseAdminView(ListView):
    model = User
    template_name = 'admin_app/admin_homepage_page.html'
    context_object_name = 'users'
    paginate_by = 10

    def get_queryset(self):
        queryset = User.objects.all().order_by('-date_joined')

        search_query = self.request.GET.get('search', '')
        if search_query:
            # Разделение поискового запроса на части
            search_terms = search_query.split()

            # Начальное фильтрование по тексту
            filters = Q()
            month = None
            day = None
            year = None

            for term in search_terms:
                # Нормализация и проверка
                normalized_month = normalize_month_name(term)
                if normalized_month:
                    month = MONTHS_RU_TO_NUM[normalized_month]

                # Проверка на день
                if re.match(r'^\d{1,2}$', term):
                    day = int(term)

                # Проверка на год
                if re.match(r'^\d{4}$', term):
                    year = int(term)

            # Фильтрация
            if year:
                if month and day:
                    filters |= Q(date_joined__year=year, date_joined__month=month, date_joined__day=day)
                elif day:
                    filters |= Q(date_joined__day=day, date_joined__year=year)
                elif month:
                    filters |= Q(date_joined__month=month, date_joined__year=year)
                else:
                    filters |= Q(date_joined__year=year)
            elif month:
                if day:
                    filters |= Q(date_joined__month=month, date_joined__day=day)
                else:
                    filters |= Q(date_joined__month=month)
            elif day:
                filters |= Q(date_joined__day=day)

            filters |= Q(first_name__icontains=search_query) | \
                       Q(last_name__icontains=search_query) | \
                       Q(patronymic__icontains=search_query) | \
                       Q(email__icontains=search_query)

            queryset = queryset.filter(filters)
        # Отправка данных
        return queryset


    def get(self, request, *args, **kwargs):
        # Обязательно использовать во всех шаблонах!!!!!
        if not AccessUtils.user_has_access(request.user):
            return HttpResponseRedirect(f'{SITE_URL}/profile/login')

        self.object_list = self.get_queryset()
        context = self.get_context_data()

        # Добавление контекста
        context['current_user'] = request.user

        # Ответ
        return self.render_to_response(context)

backend/admin_app/views/blocked_users_view.py
import re
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from django.shortcuts import redirect

from admin_app.utils.filter_users import filter_users
from users.models.users import User
from admin_app.utils.access_rights import AccessUtils
from project.settings import SITE_URL

MONTHS_RU_TO_NUM = {
    'январ': 1, 'феврал': 2, 'март': 3, 'апрел': 4, 'ма': 5, 'июн': 6,
    'июл': 7, 'август': 8, 'сентябр': 9, 'октябр': 10, 'ноябр': 11, 'декабр': 12
}

def normalize_month_name(month_name):
    # Преобразуем в нижний регистр и убираем окончания
    month_name = month_name.lower().strip()
    # Обрабатываем окончания
    for month in MONTHS_RU_TO_NUM.keys():
        if month_name.startswith(month):
            return month
    return None

class BlockedUsersView(ListView):
    model = User
    template_name = 'admin_app/blocked_users_page.html'
    context_object_name = 'users'
    paginate_by = 10

    def get_queryset(self):
        queryset = User.objects.filter(is_active=False, email_confirmed=True).order_by('-date_joined')
        search_query = self.request.GET.get('search', '')
        return filter_users(queryset, search_query)  # Используем функцию фильтрации

    def get(self, request, *args, **kwargs):
        # Обязательно использовать во всех шаблонах!!!!!
        if not AccessUtils.user_has_access(request.user):
            return HttpResponseRedirect(f'{SITE_URL}/profile/login')

        self.object_list = self.get_queryset()
        context = self.get_context_data()

        # Добавление контекста
        context['current_user'] = request.user
        context['SITE_URL'] = SITE_URL

        # Ответ
        return self.render_to_response(context)

backend/admin_app/views/unverified_users_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.views.generic import ListView

from admin_app.utils.filter_users import filter_users  # Импортируем функцию фильтрации
from users.models.users import User
from admin_app.utils.access_rights import AccessUtils
from project.settings import SITE_URL

class UnverifiedUsersView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'admin_app/unverified_users_page.html'
    context_object_name = 'users'
    paginate_by = 10

    def get_queryset(self):
        # Фильтруем пользователей по состоянию подтверждения почты и активности
        queryset = User.objects.filter(email_confirmed=False).order_by('-date_joined')
        search_query = self.request.GET.get('search', '')
        return filter_users(queryset, search_query)  # Используем функцию фильтрации

    def get(self, request, *args, **kwargs):
        if not AccessUtils.user_has_access(request.user):
            return HttpResponseRedirect(f'{SITE_URL}/profile/login')

        self.object_list = self.get_queryset()
        context = self.get_context_data()

        context['current_user'] = request.user
        context['SITE_URL'] = SITE_URL

        return self.render_to_response(context)

backend/templates/admin_app/admin_homepage_page.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2>Список пользователей</h2>

    <!-- Форма поиска -->
    <form method="get" action="{% url 'admin_homepage' %}">
        <div class="input-group mb-3">
            <input type="text" class="form-control" name="search" placeholder="Поиск пользователей" value="{{ request.GET.search }}">
            <button class="btn btn-primary" type="submit">Поиск</button>
        </div>
    </form>

    <!-- Вывод информации о текущем пользователе -->
    <p>Вы вошли как: {{ current_user.last_name }} {{ current_user.first_name }}</p>


    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Отчество</th>
                <th>Email</th>
                <th>Дата регистрации</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.patronymic }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.date_joined }}</td>
                <td>
                    <a href="{% url 'user_edit' user.pk %}" class="btn btn-primary">Редактировать</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; начало</a>
                <a href="?page={{ page_obj.previous_page_number }}">назад</a>
            {% endif %}

            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">вперед</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">конец &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
{% endblock %}

backend/templates/admin_app/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
<div class="container">

{% block content %}

{% endblock %}

</div>
</body>
</html>

backend/templates/admin_app/unverified_users_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <h2>Пользователи не подтвердившие свою почту</h2>

    <!-- Форма поиска -->
    <form method="get" action="{% url 'unverified-users' %}">
        <div class="input-group mb-3">
            <input type="text" class="form-control" name="search" placeholder="Поиск пользователей" value="{{ request.GET.search }}">
            <button class="btn btn-primary" type="submit">Поиск</button>
        </div>
    </form>

    <!-- Вывод информации о текущем пользователе -->
    <p>Вы вошли как: {{ current_user.last_name }} {{ current_user.first_name }}</p>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Отчество</th>
                <th>Email</th>
                <th>Дата регистрации</th>
                <th>Подтвержден Email</th>
                <th>Активен</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.patronymic }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.date_joined }}</td>
                    <td>
                        {% if not user.email_confirmed %}
                            Нет
                        {% else %}
                            Да
                        {% endif %}
                    </td>
                    <td>
                        {% if not user.is_active %}
                            Нет
                        {% else %}
                            Да
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; начало</a>
                <a href="?page={{ page_obj.previous_page_number }}">назад</a>
            {% endif %}

            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">вперед</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">конец &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
</div>
{% endblock %}

backend/templates/admin_app/user_edit_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>Редактирование данных пользователя</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form.first_name.label_tag }}
        <input disabled type="text" name="{{ form.first_name.name }}" id="{{ form.first_name.id_for_label }}" class="form-control" value="{{ form.first_name.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
        {{ form.last_name.label_tag }}
        <input disabled type="text" name="{{ form.last_name.name }}" id="{{ form.last_name.id_for_label }}" class="form-control" value="{{ form.last_name.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
        {{ form.patronymic.label_tag }}
        <input disabled type="text" name="{{ form.patronymic.name }}" id="{{ form.patronymic.id_for_label }}" class="form-control" value="{{ form.patronymic.value|default_if_none:''}}">
    </div>
    <div class="form-group">
        <label for="id_email">Email:</label>
        <input type="text" id="id_email" value="{{ user.email }}" class="form-control" disabled>
    </div>
    <div class="form-group">
        <label for="id_date_joined">Дата регистрации:</label>
        <input type="text" id="id_date_joined" value="{{ user.date_joined }}" class="form-control" disabled>
    </div>
{#    <div class="btn-save text-center">#}
{#        <button type="submit" class="btn btn-success btn-save">Сохранить</button>#}
{#    </div>#}
</form>

<div class="text-center mt-4">
    <div class="btn-group" role="group" aria-label="Basic example">
        <button type="button" id="assign-doctor-group" class="btn {% if user.is_doctor %}btn-danger{% else %}btn-primary{% endif %}">
            {% if user.is_doctor %}
                Убрать возможность пользователю создавать тестирования.
            {% else %}
                Дать возможность пользователю создавать тестирования.
            {% endif %}
        </button>

        {% if current_user_id != user.id %}
            <button type="button" id="assign-administrator-group" class="btn {% if user.is_administrator %}btn-danger{% else %}btn-primary{% endif %}">
                {% if user.is_administrator %}
                    Убрать возможность пользователю быть администратором.
                {% else %}
                    Дать возможность пользователю быть администратором.
                {% endif %}
            </button>


            <button type="button" id="ban-unban-user" class="btn {% if user.is_active %}btn-danger{% else %}btn-success{% endif %}">
                {% if user.is_active %}
                    Забанить пользователя
                {% else %}
                    Разбанить пользователя
                {% endif %}
            </button>

        {% else %}

            <button type="button" class="btn btn-success">
                Вы не можете снять с себя права администратора сами :)
            </button>

            <button type="button" class="btn btn-success">
                Вы не можете забанить сами себя :)
            </button>
        {% endif %}
    </div>
</div>

<div class="text-center mt-4">
    <button type="button" class="btn btn-secondary" onclick="window.history.back();">Назад</button>
</div>

<script src="{% static 'rest_framework/js/jquery-3.7.1.min.js' %}"></script>

<script>
    $(document).ready(function() {
        $('#assign-doctor-group').click(function() {
            $.ajax({
                url: '/api/user/assign-doctor-group/',
                type: 'POST',
                contentType: 'application/json',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                data: JSON.stringify({
                    user_id: {{user.id}},
                }),
                success: function(response) {
                    if (response.user_in_group) {
                        $('#assign-doctor-group').removeClass('btn-primary').addClass('btn-danger').text('Убрать возможность пользователю создавать тестирования.');
                    } else {
                        $('#assign-doctor-group').removeClass('btn-danger').addClass('btn-primary').text('Дать возможность пользователю создавать тестирования.');
                    }
                },
                error: function(xhr, status, error) {
                    console.error('Ошибка:', status, error);
                }
            });
        });


        $('#assign-administrator-group').click(function() {
            $.ajax({
                url: '/api/user/assign-administrator-group/',
                type: 'POST',
                contentType: 'application/json',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                data: JSON.stringify({
                    user_id: {{ user.id }},
                }),
                success: function(response) {
                    if (response.user_in_group) {
                        $('#assign-administrator-group').removeClass('btn-primary').addClass('btn-danger').text('Убрать возможность пользователю быть администратором.');
                    } else {
                        $('#assign-administrator-group').removeClass('btn-danger').addClass('btn-primary').text('Дать возможность пользователю быть администратором.');
                    }
                },
                error: function(xhr, status, error) {
                    console.error('Ошибка:', status, error);
                }
            });
        });

        $('#ban-unban-user').click(function() {
            var is_active = $(this).hasClass('btn-danger');
            var url = is_active ? '/api/user/users/{{ user.id }}/ban/' : '/api/user/users/{{ user.id }}/unban/';
            var new_class = is_active ? 'btn-success' : 'btn-danger';
            var new_text = is_active ? 'Разбанить пользователя' : 'Забанить пользователя';

            $.ajax({
                url: url,
                type: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                success: function(response) {
                    $('#ban-unban-user').removeClass('btn-danger btn-success').addClass(new_class).text(new_text);
                },
                error: function(xhr, status, error) {
                    console.error('Ошибка:', status, error);
                }
            });
        });
    });
</script>

<style>
    form {
        background: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

    .btn-group {
        display: flex;
        justify-content: center;
        gap: 2rem;
    }

    .btn {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }

    .btn-danger {
        background-color: #dc3545;
        color: #fff;
    }

    .btn-danger:hover {
        background-color: #c82333;
    }

    .btn-success {
        background-color: #28a745;
        color: #fff;
    }

    .btn-success:hover {
        background-color: #218838;
    }

    .btn-secondary {
        background-color: #6c757d;
        color: #fff;
    }

    .btn-save {
        margin-top: 0.2rem;
    }

    .btn-secondary:hover {
        background-color: #5a6268;
    }
</style>

{% endblock %}
